stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - Data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - Data/raw
    - src/data_preprocessing.py
    outs:
      - Data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - Data/interim
    - src/feature_engineering.py
    outs:
      - Data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - Data/processed
    - src/model_building.py
    outs:
      - model/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model/model.pkl
    - src/model_evaluation.py
    metrics:
      - reports/metrics.json